services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    networks:
      - my_network

  nestjs_app:
    build: .
    container_name: nestjs-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/movie_db
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
