version: '3.8'
services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432  # Use the new port in the environment
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: movie_db
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'  # Map to a different host port
