version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  nestjs-app:
    build: .
    container_name: nestjs-app
    environment:
      DB_HOST: postgres   # Must match the 'postgres' service name
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    depends_on:
      - postgres
    command: sh -c "./wait-for-it.sh postgres:5432 -- npm run start:prod"
    ports:
      - "3000:3000"
    restart: always
